[package]
name = "tauri-bindgen-gen-guest-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.59"

[dependencies]
tauri-bindgen-gen-rust = { path = "../gen-rust" }
tauri-bindgen-core = { path = "../bindgen-core" }
wit-parser = { path = "../wit-parser" }
heck =  { version = "0.4", features = ["unicode"] }
clap = { version = "4.1.1", features = ["derive"], optional = true }

[dev-dependencies]
wasm-bindgen = { version = "0.2.83", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.33"
serde-wasm-bindgen = "0.4.5"
js-sys = "0.3.60" 
tauri-bindgen-guest-rust = { path = "../guest-rust" }
serde = { version = "1.0.152", features = ["derive"] }

[features]
cli = ["clap"]